version: 2
jobs:
  build:
    working_directory: ~/xyz
    docker:
    - image: circleci/python:3.6.4
    steps:
    - checkout
    - run:
        name: Run tests
        command: |
          export PYTHONPATH="$PYTHONPATH:$HOME"
          
          sudo pip install coverage nose
          echo "Coverage report: " >> test-results
          coverage run --source=./abcd -m nose -w ./tests
          coverage report -m >> test-results 2>&1
          
    - store_test_results:
        path: ./reports
    - store_artifacts:
        path: test-results
        destination: tr1
workflows:
  version: 2
  workflow:
    jobs:
    - build
